baseURL = "https://dronepilot.one/"
languageCode = "en-us"
title = "Number #1 dronepilot"
theme = "simpleintro"

[params]
    mainbg = "/images/rotterdam.jpeg"
    name = "dronepilot.one"
    mainTitle = "dronepilot.one"
    mainText = "Based in the Netherlands"

[menus]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "#about"
    [[menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "#skills"
