baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "simpleintro"

[params]
    mainbg = "/images/rotterdam.jpeg"
    name = "John Doe"
    mainTitle = "Simple-intro"
    mainText = "Just simple intro theme for hugo"
