baseURL = "https://dronepilot.one/"
languageCode = "en-us"
title = "Number #1 dronepilot"
theme = "simpleintro"

[params]
    mainbg = "/images/rotterdam.jpeg"
    name = "dronepilot.one"
    mainTitle = "dronepilot.one"
    mainText = "dronepilot.one"
